package rules;

import com.kxj.entity.Message;
import java.util.concurrent.atomic.AtomicInteger;

global String temp;
global AtomicInteger count;

function void getMessage(String message) {
    System.out.println("message" + message);
}

rule "say hi"
     when
        $message: Message(Message.MessageType.HI.equals(messageType) && target!=null)
     then
        print("hi," + $message.getTarget() + ", welcome to drools\n");
     end

rule "say-goodbye"
    when
        $message: Message(Message.MessageType.GOODBYE.equals(messageType) && target!=null)
    then
        print("bye bye ," + $message.getTarget() + "\n");
    end

rule "chat-and-goodbye"
    when
        $message: Message(Message.MessageType.CHAT.equals(messageType) && target!=null)
    then
        print($message.getTarget() +  ", nice to meet you. But I have to go.");
        //将MessageType设置成GOODBYE
        $message.setMessageType(Message.MessageType.GOODBYE);
        //更新fact,以便触发规则"say-goodbye"
        update($message);
    end
